---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: bggapp-cm 
  namespace: bggns
data: 
  BGG_DB_USER: root
  BGG_PORT: '5000'
  BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

--- 
apiVersion: v1 
kind: Secret 
metadata:
  name: bgg-db-secret
  namespace: bggns
type: Opaque
data: 
  DB_PW: bXlkYnBhc3N3b3Jk